version: 2.1
orbs:
  node: circleci/node@1.1

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run sls -- deploy -s e2e-test
            - run: npm run dotEnv -- -s e2e-test
            - run: node seed-restaurants.js
  integration-test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run dotEnv -- -s e2e-test
            - run: npm run cross-env TEST_MODE=handler jest # run integration tests
  acceptance-test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run dotEnv -- -s e2e-test
            - run: npm run cross-env TEST_MODE=http jest  # run acceptance tests

  clean:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run sls -- remove -s e2e-test

workflows:
  version: 2
  dev:
    jobs:
      - build
      - deploy:
          - requires:
              - build
      - integration-test:
          requires:
            - deploy
      - acceptance-test:
          requires:
            - integration-test
      - clean:
          requires:
            - acceptance-test