version: 2.1
orbs:
  node: circleci/node@1.1

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
  integration-test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run test # run integration tests
  deploy-e2e:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run sls -- deploy -s e2e-test
            - run: npm run dotEnv -- -s e2e-test
            - run: node seed-restaurants.js
  acceptance-test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run ci:acceptance  # run acceptance tests
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run sls -- deploy
  clean-e2e:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/with-cache:
          when: always
          steps:
            - run: npm run sls -- remove -s e2e-test

workflows:
  version: 2
  dev:
    jobs:
      - build
      - integration-test:
          requires:
            - build
      - deploy-e2e:
          requires:
            - integration-test
      - acceptance-test:
          requires:
            - deploy-e2e
      - deploy:
          requires:
            - acceptance-test
      - clean-e2e:
          requires:
            - acceptance-test